# Generated by Django 3.2.19 on 2024-04-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveform',
            name='address',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='saveform',
            name='moblie',
            field=models.CharField(default=None, max_length=12),
        ),
        migrations.AlterField(
            model_name='saveform',
            name='email',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='saveform',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
