# Generated by Django 3.2.19 on 2024-04-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formdata', '0002_auto_20240420_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveform',
            name='moblie',
            field=models.IntegerField(),
        ),
    ]
