# Generated by Django 3.2.19 on 2024-04-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formdata', '0003_alter_saveform_moblie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveform',
            name='moblie',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
